services:
  acadlo-ai-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_API_BASE_URL: http://ec2-3-129-17-73.us-east-2.compute.amazonaws.com:8000
    image: acadlo-ai-frontend:latest
    container_name: acadlo-ai-frontend
    restart: unless-stopped
    env_file:
      - .env.frontend
    ports:
      - "3000:3000"
